TargetRubyVersion: 2.5.3

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/LineLength:
  Max: 120
